window.naturalRemedies = [
  { name: "Pumpkin seeds (Cucurbita pepo)", target: "Taenia, other tapeworms", evidence_level: "🌟 Moderate (systematic review)", region: "Global traditional", detail: "Cucurbitine paralyzes tapeworms. Often combined with areca nut.", safety_warning: "Generally safe when consumed as food. High doses may cause stomach upset.", dosage_note: "Adults: 20–30g raw seeds daily for 7 days. Children: reduce by weight." },
  { name: "Hagenia abyssinica (Kosso)", target: "Taenia, Ascaris", evidence_level: "📜 Traditional (East Africa)", region: "Ethiopia, East Africa", detail: "Dried flower heads used as a potent anthelmintic for centuries.", safety_warning: "⚠️ TOXIC: Contains kosotoxin. Can cause blindness, liver damage. Not recommended without medical supervision.", dosage_note: "Dosage not established – avoid self-medication." },
  { name: "Papaya seeds (Carica papaya)", target: "Ascaris, hookworm", evidence_level: "🌟 Human clinical trial", region: "Tropical", detail: "Small RCT in children: honey + papaya seeds reduced egg counts significantly.", safety_warning: "Generally safe in small amounts. Avoid in pregnancy (may stimulate uterine contractions).", dosage_note: "Children: 1 tsp crushed seeds + honey once daily for 7 days. Adults: 1–2 tbsp." },
  { name: "Artemisia annua (Sweet wormwood)", target: "Plasmodium (malaria)", evidence_level: "🌟 Strong (basis for ACT)", region: "Traditional Chinese", detail: "Source of artemisinin; not a substitute for ACT.", safety_warning: "Do not use alone for malaria – resistance risk. May cause nausea, dizziness.", dosage_note: "Only as part of WHO-approved ACT. Do not self-treat with crude plant." },
  { name: "Garlic (Allium sativum)", target: "Entamoeba, Giardia (in vitro)", evidence_level: "📊 Moderate (in vitro & animal)", region: "Global", detail: "Ajoene shows antiparasitic activity; human data limited.", safety_warning: "May increase bleeding risk if on anticoagulants. Stomach irritation.", dosage_note: "2–4 cloves raw daily for short term (max 7 days). Enteric-coated capsules preferred." },
  { name: "Tetrapleura tetraptera", target: "Onchocerca, skin parasites", evidence_level: "📜 Traditional (West Africa)", region: "Nigeria, Ghana", detail: "Fruit used for skin conditions and as an anthelmintic.", safety_warning: "Limited safety data. May cause hypotension in high doses.", dosage_note: "Traditional use: decoction of fruit – no standard dose." },
  { name: "Berberine (from barberry, goldenseal)", target: "Giardia, Entamoeba", evidence_level: "🌟 Human clinical study", region: "Traditional Chinese, Ayurveda", detail: "Comparable to metronidazole for giardiasis in one study.", safety_warning: "Avoid during pregnancy (may cause uterine contractions). Not for newborns.", dosage_note: "Adult: 300–500 mg three times daily for 2 weeks. Do not exceed 2g/day." },
  { name: "Nigella sativa (black cumin)", target: "Tapeworms", evidence_level: "📊 Field trial", region: "Middle East, South Asia", detail: "Single dose 40 mg/kg comparable to niclosamide in children.", safety_warning: "Generally safe. May lower blood pressure and blood sugar.", dosage_note: "40 mg/kg single dose (e.g., 2.5g for 60kg adult)." },
  { name: "Neem (Azadirachta indica)", target: "Filariasis, intestinal worms", evidence_level: "📜 Traditional", region: "South Asia", detail: "Leaves and oil used for parasitic infections.", safety_warning: "⚠️ Neem oil is toxic if ingested. Use only leaf extracts. Avoid in children and pregnancy.", dosage_note: "Leaf infusion: 5–10 leaves boiled in water. Neem oil for external use only." },
  { name: "Male fern (Dryopteris filix-mas)", target: "Tapeworms", evidence_level: "📜 Historical (obsolete)", region: "Europe", detail: "Historically used but toxic; no longer recommended.", safety_warning: "⚠️ HIGHLY TOXIC. Can cause blindness, liver failure, death. DO NOT USE.", dosage_note: "No safe dose – avoid completely." },
  { name: "Quassia (Quassia amara)", target: "Roundworms, pinworms", evidence_level: "📜 Traditional", region: "South America, Caribbean", detail: "Wood chips brewed as tea for worms.", safety_warning: "Bitter but generally safe. Avoid during pregnancy.", dosage_note: "1 tsp quassia chips per cup boiling water, steep 10 min. Drink 2–3 cups/day for 3 days." },
  { name: "Wormwood (Artemisia absinthium)", target: "Roundworms, pinworms", evidence_level: "📜 Traditional", region: "Europe", detail: "Contains thujone; neurotoxic in high doses.", safety_warning: "⚠️ Thujone can cause seizures, kidney failure. Do not exceed 3 weeks. Avoid in pregnancy, epilepsy.", dosage_note: "500mg dried leaf tea daily for 2 weeks maximum." },
  { name: "Thyme (Thymus vulgaris)", target: "Hookworms, ascaris", evidence_level: "📊 In vitro", region: "Mediterranean", detail: "Thymol has antiparasitic properties.", safety_warning: "Generally safe as spice. Essential oil toxic in high doses.", dosage_note: "Infusion: 1 tsp dried herb per cup, 3x daily. Not for internal use of essential oil." },
  { name: "Clove (Syzygium aromaticum)", target: "Demodex, intestinal parasites", evidence_level: "📊 In vivo (Demodex)", region: "Indonesia", detail: "Topical for Demodex; toxic if ingested.", safety_warning: "Clove oil toxic internally (liver failure). Use only topically or as spice.", dosage_note: "Topical: dilute 2 drops clove oil in 1 tbsp carrier oil for skin mites. Internal: whole cloves as spice only." },
  { name: "Oregano oil (Origanum vulgare)", target: "Blastocystis, Entamoeba", evidence_level: "📊 Small human study", region: "Mediterranean", detail: "200 mg TID for 6 weeks showed some efficacy.", safety_warning: "May irritate stomach. Do not use undiluted. Avoid in pregnancy.", dosage_note: "200mg enteric-coated capsules three times daily with food for 6 weeks max." }
];
